name: Build CV
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build CV
        run: nix run .#build
      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: main.pdf
          retention-days: 90
